# Generated by Django 5.0.6 on 2024-06-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
